[package]
name = "KAS-tutorials"
version = "0.1.0"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2018"
publish = false

[dependencies]
env_logger = "0.8"

kas = "0.8"
kas-theme = "0.8"
kas-wgpu = "0.8"
