[package]
name = "simple-window"
version = "0.1.0"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2018"
publish = false

[dependencies]
env_logger = "0.8"
kas = "0.6"
kas-theme = "0.6"
kas-wgpu = "0.6"
